const LEAST_START_COUNT_FOR_REPO = 5000;
const REPO_CRAWL_TASK_RUN_INTERVAL = 1000 * 60 * 60 * 6; // 6 hours
const PARSE_DEPENDENCIES_TASK_INTERVAL = 1000 * 60 * 60 * 6; // 6 hours
const REPO_REPROCESS_INTERVAL_DAYS = 7;

export {
    LEAST_START_COUNT_FOR_REPO,
    REPO_CRAWL_TASK_RUN_INTERVAL,
    PARSE_DEPENDENCIES_TASK_INTERVAL,
    REPO_REPROCESS_INTERVAL_DAYS
};