import dotenv from 'dotenv';
dotenv.config();

const LEAST_START_COUNT_FOR_REPO = 1499;
const REPO_CRAWL_TASK_RUN_INTERVAL = 1000 * 60 * 60 * 6; // 6 hours
const PARSE_DEPENDENCIES_TASK_INTERVAL = 1000 * 60 * 60 * 6; // 6 hours
const REPO_REPROCESS_INTERVAL_DAYS = 7;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REQUEST_USAGE_PERCENT_THRESHOLD = Number(process.env.GITHUB_REQUEST_USAGE_PERCENT_THRESHOLD) || -1;
export {
	LEAST_START_COUNT_FOR_REPO,
	REPO_CRAWL_TASK_RUN_INTERVAL,
	PARSE_DEPENDENCIES_TASK_INTERVAL,
	REPO_REPROCESS_INTERVAL_DAYS,
	GITHUB_TOKEN,
	GITHUB_REQUEST_USAGE_PERCENT_THRESHOLD as GITHUB_REQUEST_USAGE_PERCENT_THRESHOLD,
};
